#!/usr/bin/env python3
# Generates the high-precision constants embedded in v2math.h (the owned
# transcendentals of the portable player). Pure-stdlib: decimal at 60 digits.
# Re-run and diff against v2math.h if you suspect drift; the header is the
# checked-in artifact, this script is its provenance.
from decimal import Decimal, getcontext

getcontext().prec = 60
D = Decimal

def dd(x):
    """split a Decimal into a double-double (hi, lo)"""
    hi = float(x)
    lo = float(x - D(hi))
    return hi, lo

def fmt(x):
    return repr(float(x))

# ---- pi via Machin: pi = 16 atan(1/5) - 4 atan(1/239), Taylor converges fast
def atan_taylor(x):  # |x| < 1, Decimal
    s = D(0); term = x; x2 = x * x; n = 1
    while True:
        t = term / n
        if abs(t) < D(10) ** -58:
            break
        s += t if (n % 4 == 1) else -t
        term *= x2
        n += 2
    return s

PI = 16 * atan_taylor(D(1) / 5) - 4 * atan_taylor(D(1) / 239)
LN2 = D(2).ln()

def atan_d(x):  # Decimal atan for any x >= 0 via argument halving
    halvings = 0
    while abs(x) > D("0.1"):
        x = x / (1 + (1 + x * x).sqrt())
        halvings += 1
    return atan_taylor(x) * (2 ** halvings)

print("// generated by test/gen_constants.py -- do not edit by hand")
print()

# ---- exp2: table 2^(k/32), k=0..31 (double-double) + poly 2^t-1, |t|<=1/64
print("// 2^(k/32), k=0..31, double-double")
print("static const double kExp2Tab[32][2] = {")
for k in range(32):
    hi, lo = dd((D(k) / 32 * LN2).exp())
    print("  { %s, %s }," % (repr(hi), repr(lo)))
print("};")
print()
print("// 2^t - 1 = sum c[n] t^n  (c[n] = ln2^n / n!), |t| <= 1/64")
print("static const double kExp2m1C[7] = {")
f = D(1)
for n in range(1, 8):
    f *= n
    print("  %s,  // ln2^%d/%d!" % (fmt(LN2 ** n / f), n, n))
print("};")
print()

# ---- log2: table log2(1 + j/32), j=0..32 (double-double); 2/ln2
print("// log2(1 + j/32), j=0..32, double-double")
print("static const double kLog2Tab[33][2] = {")
for j in range(33):
    hi, lo = dd((1 + D(j) / 32).ln() / LN2)
    print("  { %s, %s }," % (repr(hi), repr(lo)))
print("};")
print()
print("static const double kTwoOverLn2 = %s;" % fmt(2 / LN2))
print()

# ---- sin/cos Taylor coefficients (|t| <= pi/4)
print("// sin t = t * (1 + sum s[n] t^(2n+2)) ... coeffs (-1)^n/(2n+1)!, n>=1")
print("static const double kSinC[8] = {")
f = D(1)
for n in range(1, 9):
    k = 2 * n + 1
    f = D(1)
    for i in range(2, k + 1):
        f *= i
    c = (D(-1) ** n) / f
    print("  %s,  // 1/%d!" % (fmt(c), k))
print("};")
print()
print("static const double kCosC[8] = {")
for n in range(1, 9):
    k = 2 * n
    f = D(1)
    for i in range(2, k + 1):
        f *= i
    c = (D(-1) ** n) / f
    print("  %s,  // 1/%d!" % (fmt(c), k))
print("};")
print()

# ---- atan: table atan(j/8), j=0..8 (double-double); odd Taylor |t|<=1/16
print("// atan(j/8), j=0..8, double-double")
print("static const double kAtanTab[9][2] = {")
for j in range(9):
    hi, lo = dd(atan_d(D(j) / 8))
    print("  { %s, %s }," % (repr(hi), repr(lo)))
print("};")
print()

# ---- pi family (double-double)
for name, val in [("kPi", PI), ("kPiO2", PI / 2), ("kTwoPi", 2 * PI)]:
    hi, lo = dd(val)
    print("static const double %sHi = %s, %sLo = %s;" % (name, repr(hi), name, repr(lo)))
